import os

CORE_DIR = os.path.join(os.path.dirname(__file__), "..", "..")

MODELS_DIR = os.path.join(CORE_DIR, "models")

ASSETS_DIR = os.path.join(CORE_DIR, "assets")

DB_DIR = os.path.join(CORE_DIR, "db")

IMAGES_DIR = os.path.join(ASSETS_DIR, "img")
ICONS_DIR = os.path.join(IMAGES_DIR, "icons")
TMP_DIR = os.path.join(ASSETS_DIR, "tmp")

DEFAULT_SILENCE_TIMER = 2

WHISPER_MODEL_SIZE = "base.en"
WHISPER_MODEL_PATH = os.path.join(MODELS_DIR, WHISPER_MODEL_SIZE)

WHISPER_LANGUAGES = {
    "afrikaans": "af",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "azerbaijani": "az",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bosnian": "bs",
    "bulgarian": "bg",
    "catalan": "ca",
    "cebuano": "ceb",
    "chichewa": "ny",
    "chinese (simplified)": "zh-CN",
    "chinese (traditional)": "zh-TW",
    "corsican": "co",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "esperanto": "eo",
    "estonian": "et",
    "filipino": "tl",
    "finnish": "fi",
    "french": "fr",
    "frisian": "fy",
    "galician": "gl",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "haitian creole": "ht",
    "hausa": "ha",
    "hawaiian": "haw",
    "hebrew": "he",
    "hindi": "hi",
    "hmong": "hmn",
    "hungarian": "hu",
    "icelandic": "is",
    "igbo": "ig",
    "indonesian": "id",
    "irish": "ga",
    "italian": "it",
    "japanese": "ja",
    "javanese": "jw",
    "kannada": "kn",
    "kazakh": "kk",
    "khmer": "km",
    "korean": "ko",
    "kurdish (kurmanji)": "ku",
    "kyrgyz": "ky",
    "lao": "lo",
    "latin": "la",
    "latvian": "lv",
    "lithuanian": "lt",
    "luxembourgish": "lb",
    "macedonian": "mk",
    "malagasy": "mg",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "maori": "mi",
    "marathi": "mr",
    "mongolian": "mn",
    "myanmar (burmese)": "my",
    "nepali": "ne",
    "norwegian": "no",
    "odia": "or",
    "pashto": "ps",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "romanian": "ro",
    "russian": "ru",
    "samoan": "sm",
    "scots gaelic": "gd",
    "serbian": "sr",
    "sesotho": "st",
    "shona": "sn",
    "sindhi": "sd",
    "sinhala": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "somali": "so",
    "spanish": "es",
    "sundanese": "su",
    "swahili": "sw",
    "swedish": "sv",
    "tajik": "tg",
    "tamil": "ta",
    "telugu": "te",
    "thai": "th",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "vietnamese": "vi",
    "welsh": "cy",
    "xhosa": "xh",
    "yiddish": "yi",
    "yoruba": "yo",
    "zulu": "zu",
}

# Rule-based corrections for phonetically similar words
CORRECTIONS = {
    "moss": "mouse",
    "moose": "mouse",
    "curse": "cursor",
    "curser": "cursor",
    "right": "write",
    "rite": "right",
    "left": "lift",
    "center": "sender",
    "middle": "medal",
    "scroll": "stroll",
    "move": "mood",
    "press": "dress",
    "enter": "inter",
    "delete": "dilute",
    "space": "pace",
    "tab": "tap",
    "escape": "cape",
    "copy": "coffee",
    "paste": "taste",
    "cut": "cup",
    "undo": "unto",
    "redo": "read",
    "select": "collect",
    "find": "fine",
    "replace": "replay",
    "save": "safe",
    "open": "hoping",
    "close": "clothes",
    "quit": "quick",
    "exit": "exist",
    "minimize": "minimized",
    "maximize": "maximized",
    "restore": "restorer",
    "refresh": "fresh",
    "reload": "reloaded",
    "zoom": "boom",
    "screen": "scream",
    "print": "sprint",
    "mute": "moot",
    "unmute": "unmoot",
    "volume": "volumes",
    "play": "lay",
    "pause": "paws",
    "stop": "top",
    "next": "nest",
    "previous": "previews",
    "forward": "foreword",
    "backward": "backwards",
    "rewind": "remind",
    "fast": "last",
}